import type { Metadata } from "next";
import "./globals.css";
import { type ThemeProviderProps } from 'next-themes'
import RootLayoutProvider from "@/components/RootLayoutProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, ...props }: Readonly<ThemeProviderProps>) {

  return (
    <RootLayoutProvider {...props}>
    {children}
    </RootLayoutProvider>
  );
}
